<a href="https://colab.research.google.com/github/realyou0312/AED_Project/blob/main/AHP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 가중치 구하기

In [ ]:
import pandas as pd
import numpy as np
from scipy.stats.mstats import gmean

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
survey = pd.read_csv('/content/drive/MyDrive/설문조사.csv', encoding='euc-kr')

In [ ]:
survey = pd.DataFrame(survey.iloc[:,2:5])
survey

Q_1  Q_2  Q_3
0    9    9    9
1    1    9    3
2    9    9    9
3    7    3    3
4    7    9    9
5    5    5    5
6    5    5    5
7    7    5    7
8    9    7    5

In [ ]:
list_array = []
for i in range(len(survey.index)):
  survey_array = np.array([[1, 1/(survey.iloc[i,0]), 1/(survey.iloc[i,1])],
                           [survey.iloc[i,0], 1, 1/(survey.iloc[i,2])],
                           [survey.iloc[i,1], survey.iloc[i,2], 1]])
  list_array.append(survey_array)
list_array

[array([[1.        , 0.11111111, 0.11111111],
        [9.        , 1.        , 0.11111111],
        [9.        , 9.        , 1.        ]]),
 array([[1.        , 1.        , 0.11111111],
        [1.        , 1.        , 0.33333333],
        [9.        , 3.        , 1.        ]]),
 array([[1.        , 0.11111111, 0.11111111],
        [9.        , 1.        , 0.11111111],
        [9.        , 9.        , 1.        ]]),
 array([[1.        , 0.14285714, 0.33333333],
        [7.        , 1.        , 0.33333333],
        [3.        , 3.        , 1.        ]]),
 array([[1.        , 0.14285714, 0.11111111],
        [7.        , 1.        , 0.11111111],
        [9.        , 9.        , 1.        ]]),
 array([[1. , 0.2, 0.2],
        [5. , 1. , 0.2],
        [5. , 5. , 1. ]]),
 array([[1. , 0.2, 0.2],
        [5. , 1. , 0.2],
        [5. , 5. , 1. ]]),
 array([[1.        , 0.14285714, 0.2       ],
        [7.        , 1.        , 0.14285714],
        [5.        , 7.        , 1.        ]]),
 array

In [ ]:
weight_sum =np.array([[0.],[0.],[0.]])
cnt = 0

for i in range(len(list_array)):
  num = pd.DataFrame(list_array[i])
  num.index = ['수요', '처치', '관리']
  num.columns = ['수요', '처치', '관리']
  
  Q1_sum = num.iloc[:,0].sum() 
  Q2_sum = num.iloc[:,1].sum() 
  Q3_sum = num.iloc[:,2].sum() 

  #정규화
  num.iloc[:,0] = num.iloc[:,0] / Q1_sum
  num.iloc[:,1] = num.iloc[:,1] / Q2_sum
  num.iloc[:,2] = num.iloc[:,2] / Q3_sum 
  
  #요인별 가중치 행의 합
  Q1_weight = num.iloc[0,:].sum() 
  Q2_weight = num.iloc[1,:].sum() 
  Q3_weight = num.iloc[2,:].sum() 

  #가중치 행렬 생성
  weight_array = np.array([[Q1_weight / 3],
                          [Q2_weight / 3 ],
                          [Q3_weight / 3]])
  
  array_weight = (num @ weight_array)
  
  gamma_array = (array_weight / weight_array)

  gamma = gamma_array.iloc[:,0].sum()
  
  CR = (gamma - 3) / 2 / 0.58
  
  if CR < 0.1:
    weight_sum += weight_array
    cnt += 1

final_CR = (weight_sum / cnt)
print(final_CR)

[[0.0787015 ]
 [0.24647026]
 [0.67482824]]


In [ ]:
0.24647026/2

0.12323513